/**
 * home/routes.js — public home-page data (mounted at /api/home).
 *
 * GET /api/home/hero → { stats, media, slogans } for the landing hero:
 *   - stats:   site totals (vods, live sessions, chat messages, users, weekly-active, live now)
 *   - media:   a shuffled mix of live streams + recent VODs + clips + pastes for the floating
 *              thumbnail collage (thumbnail, title, type, link)
 *   - slogans: { audiences, quips } rotating hero copy. AI-generated by slogan-job (cached in
 *              site_settings), with a rich static fallback so the hero is always lively.
 */
'use strict';
const express = require('express');
const path = require('path');
const db = require('../db/database');

const router = express.Router();

// ── Static fallback slogans (used until the AI job fills site_settings, or if AI is off) ──
const FALLBACK_AUDIENCES = [
    'stealth campers', 'digital nomads', 'IRL streamers', 'desktop gamers', 'van dwellers',
    'thru-hikers', 'tinkerers', 'night-shift coders', 'overlanders', 'urban explorers',
    'people who left Twitch', 'the terminally online', 'garage inventors', 'ham radio nerds',
    'lofi enjoyers', 'campfire philosophers', 'the chronically curious', 'weekend makers',
    'retro hardware freaks', 'anyone with a webcam and a dream', 'backyard astronomers',
    'keyboard warriors (literal)', 'off-grid dreamers', 'the beautifully unhinged',
];
const FALLBACK_QUIPS = [
    'No ads. No investors. No suits. Just vibes.',
    'The stream site that pays rent in good vibes.',
    'Open source and proud of it.',
    'Built by hobos, for hobos.',
    'Your stream, your rules, your campfire.',
    "Corporate streaming? We don't know her.",
    'Low latency, high chaos.',
    'Go live in seconds — regret it in real time.',
    'Powered by caffeine and spite.',
    'The internet campfire everyone forgot they wanted.',
    'Clip it before it happens.',
    'Free forever, because we forgot to add a paywall.',
    'Where the wifi is questionable and the community is not.',
    'Stream from a van. We support that lifestyle.',
    'Now with 100% more tent.',
];

function _shuffle(arr) {
    const a = arr.slice();
    for (let i = a.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [a[i], a[j]] = [a[j], a[i]]; }
    return a;
}

function _pasteThumb(p) {
    if (p.type === 'screenshot' && p.screenshot_path) {
        try { return `/data/pastes/screenshots/${path.basename(p.screenshot_path)}`; } catch { /* */ }
    }
    return null;
}

// Assemble the floating-collage media pool from every content type.
function heroMedia() {
    const items = [];
    try {
        for (const s of (db.getLiveStreams() || []).slice(0, 8)) {
            items.push({ kind: 'live', title: s.title || 'Live now', thumbnail: s.thumbnail_url || null, href: `/@${s.username}`, username: s.username });
        }
    } catch { /* */ }
    try {
        for (const v of (db.getRecentVods(12, 0) || [])) {
            items.push({ kind: 'vod', title: v.title || 'VOD', thumbnail: v.thumbnail_url || `/api/thumbnails/generate/vod/${v.id}`, href: `/vod/${v.id}`, username: v.username });
        }
    } catch { /* */ }
    try {
        for (const c of (db.getPublicClips(12, 0) || [])) {
            items.push({ kind: 'clip', title: c.title || 'Clip', thumbnail: c.thumbnail_url || `/api/thumbnails/generate/clip/${c.id}`, href: `/clip/${c.id}`, username: c.username });
        }
    } catch { /* */ }
    try {
        const pr = db.listPastes({ visibility: 'public', limit: 12 });
        const rows = Array.isArray(pr) ? pr : (pr && pr.pastes) || [];
        for (const p of rows) {
            items.push({
                kind: 'paste', title: p.title || 'Paste', thumbnail: _pasteThumb(p),
                text: p.type === 'screenshot' ? null : String(p.content || '').slice(0, 140),
                href: `/p/${p.slug}`, username: p.username,
            });
        }
    } catch { /* */ }
    // Interleave types so the collage isn't clumped, then shuffle for variety per request.
    return _shuffle(items).slice(0, 28);
}

// An audience must be JUST the noun phrase that completes "Live streaming for ___" — strip any
// baked-in "(live) streaming for" / "for" prefix (some LLM outputs include it → "Live streaming
// for live streaming for nomads") and trailing punctuation.
function _cleanAudience(raw) {
    return String(raw == null ? '' : raw)
        .replace(/^\s*(live\s+)?streaming\s+for\s+/i, '')
        .replace(/^\s*for\s+/i, '')
        .replace(/^["'‘’“”\-\s]+|["'‘’“”\s]+$/g, '')
        .replace(/[.!,;:]+$/, '')
        .trim();
}

function heroSlogans() {
    let s = null;
    try {
        s = db.getSetting('home_hero_slogans');
        if (typeof s === 'string') s = JSON.parse(s);
    } catch { s = null; }
    const aiAud = (s && Array.isArray(s.audiences)) ? s.audiences.map(_cleanAudience).filter(a => a && a.length <= 60) : [];
    const aiQuips = (s && Array.isArray(s.quips)) ? s.quips.filter(q => q && String(q).length <= 120) : [];
    const hasAi = aiAud.length >= 4 || aiQuips.length >= 4;
    // Purely AI once we have a daily batch; the static set is only the cold-start / AI-off default.
    return {
        audiences: _shuffle(Array.from(new Set(hasAi ? aiAud : FALLBACK_AUDIENCES))),
        quips: _shuffle(Array.from(new Set(hasAi ? aiQuips : FALLBACK_QUIPS))),
        ai: hasAi,
    };
}

router.get('/hero', (req, res) => {
    try {
        res.set('Cache-Control', 'public, max-age=20');
        res.json({ stats: db.getHomeStats(), media: heroMedia(), slogans: heroSlogans() });
    } catch (err) {
        console.error('[Home] hero error:', err.message);
        res.status(500).json({ error: 'Failed to load hero' });
    }
});

module.exports = router;
module.exports.FALLBACK_AUDIENCES = FALLBACK_AUDIENCES;
module.exports.FALLBACK_QUIPS = FALLBACK_QUIPS;
