/**
 * SEO for the SPA — per-route server-side meta / Open Graph / Twitter / JSON-LD injection,
 * a no-JS crawlable content snapshot, and a dynamic sitemap. Cached throughout.
 *
 * The app is a client-rendered SPA (server/index.js serves public/index.html for every route),
 * so crawlers/AI scrapers see an empty shell. This middleware intercepts the HTML routes we
 * care about (home, vods/clips/pastes lists, and vod/clip/paste detail pages), and rewrites the
 * <head> with route-specific machine-readable metadata + drops a <noscript> content snapshot so
 * no-JS scrapers get real content. Everything is cached so it adds ~no per-request DB cost.
 */
'use strict';
const fs = require('node:fs');
const path = require('node:path');
const db = require('../db/database');
let config = null; try { config = require('../config'); } catch { /* */ }

const INDEX_HTML_PATH = path.join(__dirname, '../../public/index.html');
const SITE_NAME = 'HoboStreamer';
const DEFAULT_OG_IMAGE = '/og-image.png';

function baseUrl() {
    let b = (config && config.baseUrl) || 'https://hobostreamer.com';
    if (/localhost|127\.0\.0\.1/.test(b)) b = 'https://hobostreamer.com'; // never emit localhost in public meta
    return b.replace(/\/+$/, '');
}
function abs(url) {
    if (!url) return '';
    if (/^https?:\/\//i.test(url)) return url;
    return baseUrl() + (url.startsWith('/') ? url : '/' + url);
}
// HTML-escape for text nodes / attribute values.
function esc(s) {
    return String(s == null ? '' : s)
        .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}
// Collapse to a clean single-line meta-description-safe string.
function clean(s, max) {
    let t = String(s == null ? '' : s).replace(/\s+/g, ' ').trim();
    if (max && t.length > max) t = t.slice(0, max - 1).replace(/\s+\S*$/, '') + '…';
    return t;
}
function isoDate(dt) {
    try {
        if (!dt) return null;
        const d = new Date(String(dt).includes('T') ? dt : String(dt).replace(' ', 'T') + 'Z');
        return isNaN(d.getTime()) ? null : d.toISOString();
    } catch { return null; }
}
// Seconds → ISO-8601 duration (PT#H#M#S) for VideoObject.
function iso8601Duration(sec) {
    sec = Math.max(0, Math.floor(Number(sec) || 0));
    const h = Math.floor(sec / 3600), m = Math.floor((sec % 3600) / 60), s = sec % 60;
    return 'PT' + (h ? h + 'H' : '') + (m ? m + 'M' : '') + (s || (!h && !m) ? s + 'S' : '');
}
function jsonLd(obj) {
    // Escape "<" so a value can never break out of the <script> block.
    return `<script type="application/ld+json">${JSON.stringify(obj).replace(/</g, '\\u003c')}</script>`;
}

// ── Build the per-route metadata object ────────────────────────────────────────────────────
// Returns { title, description, canonicalPath, image, ogType, robots, jsonLd:[...], snapshot }
// or null to fall through (unknown / private / not found).

function _pageMeta(routePath) {
    const p = routePath.replace(/\/+$/, '') || '/';
    const bu = baseUrl();

    // Home
    if (p === '/') {
        return {
            title: 'HoboStreamer — Free Open-Source Live Streaming Platform',
            description: 'Free, open-source live streaming with sub-second WebRTC, OBS/RTMP & CLI ingest, auto VODs & AI clips, restreaming to Twitch/YouTube/Kick, global chat, viewer-controlled robots, and 200+ free tools.',
            canonicalPath: '/', image: DEFAULT_OG_IMAGE, ogType: 'website', robots: 'index,follow',
            jsonLd: [], snapshot: '', // home already ships rich static JSON-LD; keep it lean
        };
    }
    // List pages
    if (p === '/vods') return _listMeta('vods', 'VODs', 'Browse recorded live streams (VODs) on HoboStreamer — auto-recorded broadcasts with AI overviews and searchable transcripts.', () => (db.getRecentVods(24, 0) || []).map(v => ({ url: `/vod/${v.id}`, name: v.title || 'VOD' })));
    if (p === '/clips') return _listMeta('clips', 'Clips', 'Watch the best clips from HoboStreamer live streams — highlights clipped by viewers and auto-generated by AI.', () => (db.getPublicClips(24, 0) || []).map(c => ({ url: `/clip/${c.id}`, name: c.title || 'Clip' })));
    if (p === '/pastes') return _listMeta('pastes', 'Pastes', 'Code, text and screenshot pastes shared on HoboStreamer — a Pastebin built into the streaming network, with AI summaries.', () => { const r = db.listPastes({ visibility: 'public', limit: 24, offset: 0 }); return ((r && r.pastes) || []).map(x => ({ url: `/p/${x.slug}`, name: x.title || 'Paste' })); });

    // Detail pages
    let m;
    if ((m = p.match(/^\/vod\/(\d+)$/))) return _vodMeta(parseInt(m[1], 10));
    if ((m = p.match(/^\/clip\/(\d+)$/))) return _clipMeta(parseInt(m[1], 10));
    if ((m = p.match(/^\/p\/([A-Za-z0-9_-]+)$/))) return _pasteMeta(m[1]);
    if ((m = p.match(/^\/@([A-Za-z0-9_.-]+)$/))) return _channelMeta(m[1]);

    return null;
    void bu;
}

function _channelMeta(username) {
    let ch; try { ch = db.getChannelByUsername(username); } catch { ch = null; }
    if (!ch) return null;
    const name = ch.display_name || ch.username || username;
    const handle = '@' + (ch.username || username);
    let ov = null;
    try { ov = db.getStreamerOverview ? db.getStreamerOverview(ch.user_id) : null; } catch { /* */ }
    let followers = 0;
    try { followers = db.getFollowerCount ? (db.getFollowerCount(ch.user_id) || 0) : 0; } catch { /* */ }
    const bio = clean(ch.bio || '', 300);
    const aiShort = clean((ov && (ov.overview_short || ov.overview)) || '', 220);
    const desc = clean(bio || aiShort || `${name} (${handle}) streams live on ${SITE_NAME}. Watch their live streams, VODs and clips.`, 200);
    const image = ch.avatar_url ? abs(ch.avatar_url) : DEFAULT_OG_IMAGE;
    const canonicalPath = `/${handle}`;
    const person = {
        '@type': 'Person', name: clean(name, 80), alternateName: handle, url: abs(canonicalPath),
        image: image !== DEFAULT_OG_IMAGE ? image : undefined,
        description: desc,
        interactionStatistic: followers ? { '@type': 'InteractionCounter', interactionType: 'https://schema.org/FollowAction', userInteractionCount: followers } : undefined,
    };
    const profile = { '@context': 'https://schema.org', '@type': 'ProfilePage', name: `${name} (${handle})`, url: abs(canonicalPath), mainEntity: person };
    const snapshot = _detailSnapshot({
        title: `${name} (${handle})`, byline: followers ? `${followers} follower${followers === 1 ? '' : 's'} on ${SITE_NAME}` : null,
        desc: bio || null, overview: (ov && ov.overview) || null, transcript: null,
        canonicalPath, watchLabel: `Visit ${name}'s channel`,
    });
    return {
        title: `${name} (${handle}) — ${SITE_NAME}`, description: desc,
        canonicalPath, image, ogType: 'profile', robots: 'index,follow',
        jsonLd: [profile, _breadcrumb([{ name: 'Home', url: '/' }, { name: name, url: canonicalPath }])],
        snapshot,
    };
}

function _listMeta(slug, label, description, itemsFn) {
    let items = [];
    try { items = (itemsFn() || []).slice(0, 24); } catch { /* */ }
    const canonical = abs('/' + slug);
    const list = {
        '@context': 'https://schema.org', '@type': 'CollectionPage',
        name: `${label} — ${SITE_NAME}`, url: canonical, description,
        mainEntity: {
            '@type': 'ItemList',
            itemListElement: items.map((it, i) => ({ '@type': 'ListItem', position: i + 1, url: abs(it.url), name: clean(it.name, 110) })),
        },
    };
    const snapshot = `<h1>${esc(label)} on ${SITE_NAME}</h1><p>${esc(description)}</p>` +
        (items.length ? `<ul>${items.map(it => `<li><a href="${esc(abs(it.url))}">${esc(clean(it.name, 110))}</a></li>`).join('')}</ul>` : '');
    return {
        title: `${label} — ${SITE_NAME}`, description, canonicalPath: '/' + slug,
        image: DEFAULT_OG_IMAGE, ogType: 'website', robots: 'index,follow',
        jsonLd: [list, _breadcrumb([{ name: 'Home', url: '/' }, { name: label, url: '/' + slug }])],
        snapshot,
    };
}

function _authorLd(name) { return name ? { '@type': 'Person', name: clean(name, 80) } : undefined; }

function _vodMeta(id) {
    let v; try { v = db.getVodById(id); } catch { v = null; }
    if (!v) return null;
    const indexable = Number(v.is_public) === 1 && (!v.visibility || v.visibility === 'public');
    const author = v.display_name || v.username;
    const title = clean(v.title || `${author ? author + "'s " : ''}stream VOD`, 80);
    const desc = clean(v.ai_overview_short || v.ai_overview || v.description || `Recorded live stream${author ? ' by ' + author : ''} on ${SITE_NAME}.`, 200);
    const image = v.thumbnail_url ? abs(v.thumbnail_url) : abs(`/api/thumbnails/generate/vod/${id}`);
    const canonicalPath = `/vod/${id}`;
    const vo = {
        '@context': 'https://schema.org', '@type': 'VideoObject',
        name: title, description: desc, thumbnailUrl: [image],
        uploadDate: isoDate(v.created_at) || undefined,
        duration: iso8601Duration(v.duration_seconds),
        contentUrl: abs(canonicalPath), embedUrl: abs(canonicalPath),
        interactionStatistic: { '@type': 'InteractionCounter', interactionType: 'https://schema.org/WatchAction', userInteractionCount: Number(v.view_count) || 0 },
        author: _authorLd(author), publisher: { '@type': 'Organization', name: SITE_NAME, url: baseUrl() },
    };
    const snapshot = _detailSnapshot({
        title, byline: author ? `Streamed by ${author}` : null, desc,
        overview: v.ai_overview, transcript: v.ai_transcript, canonicalPath, watchLabel: 'Watch this VOD',
    });
    return {
        title: `${title}${author ? ' — ' + author : ''} | ${SITE_NAME}`, description: desc,
        canonicalPath, image, ogType: 'video.other', robots: indexable ? 'index,follow' : 'noindex,follow',
        video: { duration: Math.floor(Number(v.duration_seconds) || 0) },
        jsonLd: [vo, _breadcrumb([{ name: 'Home', url: '/' }, { name: 'VODs', url: '/vods' }, { name: title, url: canonicalPath }])],
        snapshot,
    };
}

function _clipMeta(id) {
    let c; try { c = db.getClipById(id); } catch { c = null; }
    if (!c) return null;
    const indexable = Number(c.is_public) === 1 && (!c.visibility || c.visibility === 'public');
    const creator = c.display_name || c.username;
    const title = clean(c.title || 'Clip', 80);
    const desc = clean(c.ai_overview_short || c.ai_overview || c.description || `A clip from a live stream on ${SITE_NAME}${creator ? ', clipped by ' + creator : ''}.`, 200);
    const image = c.thumbnail_url ? abs(c.thumbnail_url) : abs(`/api/thumbnails/generate/clip/${id}`);
    const canonicalPath = `/clip/${id}`;
    const vo = {
        '@context': 'https://schema.org', '@type': 'VideoObject',
        name: title, description: desc, thumbnailUrl: [image],
        uploadDate: isoDate(c.created_at) || undefined,
        duration: iso8601Duration(c.duration_seconds),
        contentUrl: abs(canonicalPath), embedUrl: abs(canonicalPath),
        interactionStatistic: { '@type': 'InteractionCounter', interactionType: 'https://schema.org/WatchAction', userInteractionCount: Number(c.view_count) || 0 },
        author: _authorLd(creator), publisher: { '@type': 'Organization', name: SITE_NAME, url: baseUrl() },
    };
    const snapshot = _detailSnapshot({
        title, byline: creator ? `Clipped by ${creator}` : null, desc,
        overview: c.ai_overview, transcript: c.ai_transcript, canonicalPath, watchLabel: 'Watch this clip',
    });
    return {
        title: `${title} — clip | ${SITE_NAME}`, description: desc,
        canonicalPath, image, ogType: 'video.other', robots: indexable ? 'index,follow' : 'noindex,follow',
        video: { duration: Math.floor(Number(c.duration_seconds) || 0) },
        jsonLd: [vo, _breadcrumb([{ name: 'Home', url: '/' }, { name: 'Clips', url: '/clips' }, { name: title, url: canonicalPath }])],
        snapshot,
    };
}

function _pasteMeta(slug) {
    let p; try { p = db.getPasteBySlug(slug); } catch { p = null; }
    if (!p) return null;
    const isScreenshot = p.type === 'screenshot';
    // Only public, non-NSFW, non-burn pastes are indexable.
    const indexable = (p.visibility === 'public' || p.visibility == null) && !Number(p.is_nsfw) && !Number(p.burn_after_read);
    const author = p.display_name || p.username;
    const title = clean(p.title || (isScreenshot ? 'Screenshot' : 'Paste'), 80);
    const desc = clean(p.ai_summary || (isScreenshot ? `A screenshot shared on ${SITE_NAME}.` : String(p.content || '').slice(0, 220)) || `A paste on ${SITE_NAME}.`, 200);
    let image = DEFAULT_OG_IMAGE;
    if (isScreenshot && p.screenshot_path) image = abs(`/data/pastes/screenshots/${path.basename(p.screenshot_path)}`);
    const canonicalPath = `/p/${slug}`;
    let tags = [];
    try { tags = p.ai_tags ? JSON.parse(p.ai_tags) : []; } catch { tags = []; }
    const ld = isScreenshot
        ? { '@context': 'https://schema.org', '@type': 'ImageObject', name: title, description: desc, contentUrl: image, uploadDate: isoDate(p.created_at) || undefined, author: _authorLd(author) }
        : { '@context': 'https://schema.org', '@type': 'SoftwareSourceCode', name: title, description: desc, programmingLanguage: p.language && p.language !== 'text' ? p.language : undefined, dateCreated: isoDate(p.created_at) || undefined, author: _authorLd(author), keywords: (Array.isArray(tags) && tags.length) ? tags.join(', ') : undefined };
    const snapshot = _detailSnapshot({
        title, byline: author ? `Shared by ${author}` : null, desc,
        overview: p.ai_summary, transcript: (!isScreenshot ? String(p.content || '').slice(0, 1200) : null),
        canonicalPath, watchLabel: 'View this paste',
    });
    return {
        title: `${title} — paste | ${SITE_NAME}`, description: desc,
        canonicalPath, image, ogType: isScreenshot ? 'article' : 'article', robots: indexable ? 'index,follow' : 'noindex,follow',
        jsonLd: [ld, _breadcrumb([{ name: 'Home', url: '/' }, { name: 'Pastes', url: '/pastes' }, { name: title, url: canonicalPath }])],
        snapshot,
    };
}

function _breadcrumb(items) {
    return {
        '@context': 'https://schema.org', '@type': 'BreadcrumbList',
        itemListElement: items.map((it, i) => ({ '@type': 'ListItem', position: i + 1, name: clean(it.name, 90), item: abs(it.url) })),
    };
}
function _detailSnapshot({ title, byline, desc, overview, transcript, canonicalPath, watchLabel }) {
    let html = `<article><h1>${esc(title)}</h1>`;
    if (byline) html += `<p class="byline">${esc(byline)}</p>`;
    if (desc) html += `<p>${esc(desc)}</p>`;
    if (overview && String(overview).trim()) html += `<section><h2>AI overview</h2><p>${esc(clean(overview, 1200))}</p></section>`;
    if (transcript && String(transcript).trim()) html += `<section><h2>Transcript</h2><p>${esc(clean(transcript, 1500))}</p></section>`;
    html += `<p><a href="${esc(abs(canonicalPath))}">${esc(watchLabel || 'Open')}</a> on ${SITE_NAME}.</p></article>`;
    return html;
}

// ── Inject metadata into the base index.html ────────────────────────────────────────────────
let _baseHtml = null;
function _base() {
    if (_baseHtml == null) {
        try { _baseHtml = fs.readFileSync(INDEX_HTML_PATH, 'utf8'); } catch { _baseHtml = ''; }
    }
    return _baseHtml;
}
function _headBlock(meta) {
    const canonical = abs(meta.canonicalPath || '/');
    const img = abs(meta.image || DEFAULT_OG_IMAGE);
    const parts = [
        `<title>${esc(meta.title)}</title>`,
        `<meta name="description" content="${esc(meta.description)}">`,
        `<meta name="robots" content="${esc(meta.robots || 'index,follow')}">`,
        `<link rel="canonical" href="${esc(canonical)}">`,
        `<meta property="og:type" content="${esc(meta.ogType || 'website')}">`,
        `<meta property="og:site_name" content="${SITE_NAME}">`,
        `<meta property="og:title" content="${esc(meta.title)}">`,
        `<meta property="og:description" content="${esc(meta.description)}">`,
        `<meta property="og:url" content="${esc(canonical)}">`,
        `<meta property="og:image" content="${esc(img)}">`,
        `<meta property="og:locale" content="en_US">`,
        `<meta name="twitter:card" content="${meta.video ? 'player' : 'summary_large_image'}">`,
        `<meta name="twitter:title" content="${esc(meta.title)}">`,
        `<meta name="twitter:description" content="${esc(meta.description)}">`,
        `<meta name="twitter:image" content="${esc(img)}">`,
    ];
    if (meta.video && meta.video.duration) {
        parts.push(`<meta property="og:video:duration" content="${meta.video.duration}">`);
        parts.push(`<meta property="video:duration" content="${meta.video.duration}">`);
    }
    for (const l of (meta.jsonLd || [])) parts.push(jsonLd(l));
    return '\n' + parts.map(x => '    ' + x).join('\n') + '\n';
}
function render(meta) {
    let html = _base();
    if (!html) return null;
    // Strip the hardcoded homepage tags we're replacing (title, description, canonical, all
    // og:/twitter:, robots) so there are no duplicates.
    html = html
        .replace(/\s*<title>[\s\S]*?<\/title>/i, '')
        .replace(/\s*<meta\s+name=["']description["'][^>]*>/ig, '')
        .replace(/\s*<meta\s+name=["']robots["'][^>]*>/ig, '')
        .replace(/\s*<link\s+rel=["']canonical["'][^>]*>/ig, '')
        .replace(/\s*<meta\s+property=["']og:[^"']*["'][^>]*>/ig, '')
        .replace(/\s*<meta\s+name=["']twitter:[^"']*["'][^>]*>/ig, '');
    // Insert the fresh head block just before </head>.
    html = html.replace(/<\/head>/i, _headBlock(meta) + '</head>');
    // Drop a no-JS crawlable snapshot right after <body> (real users run the SPA, which ignores it).
    if (meta.snapshot) {
        html = html.replace(/(<body[^>]*>)/i, `$1\n<noscript><div id="seo-snapshot" style="max-width:820px;margin:0 auto;padding:24px;">${meta.snapshot}</div></noscript>`);
    }
    return html;
}

// ── Cache (rendered HTML per path, short TTL) ───────────────────────────────────────────────
const _cache = new Map(); // path -> { html, at }
const CACHE_TTL_MS = 5 * 60 * 1000;
const CACHE_MAX = 500;
function _cacheGet(key) { const e = _cache.get(key); return e && (Date.now() - e.at) < CACHE_TTL_MS ? e.html : null; }
function _cacheSet(key, html) {
    if (_cache.size >= CACHE_MAX) { const first = _cache.keys().next().value; _cache.delete(first); }
    _cache.set(key, { html, at: Date.now() });
}

const SEO_ROUTE_RE = /^\/(?:$|vods$|clips$|pastes$|vod\/\d+$|clip\/\d+$|p\/[A-Za-z0-9_-]+$|@[A-Za-z0-9_.-]+$)/;

function middleware(req, res, next) {
    if (req.method !== 'GET') return next();
    const p = (req.path || '/').replace(/\/+$/, '') || '/';
    if (!SEO_ROUTE_RE.test(p)) return next();
    // Only rewrite HTML navigations, not fetch()/XHR/asset probes.
    if (req.headers.accept && req.headers.accept.indexOf('text/html') === -1) return next();
    try {
        const cached = _cacheGet(p);
        if (cached) { res.set('Cache-Control', 'public, max-age=300'); res.type('html'); return res.send(cached); }
        const meta = _pageMeta(p);
        if (!meta) return next(); // unknown / not found → let the SPA 404 client-side
        const html = render(meta);
        if (!html) return next();
        _cacheSet(p, html);
        res.set('Cache-Control', 'public, max-age=300');
        res.type('html');
        return res.send(html);
    } catch (e) {
        console.warn('[SEO] render failed for', p, '-', e.message);
        return next();
    }
}

// ── Dynamic sitemap.xml (cached ~1h) ────────────────────────────────────────────────────────
let _sitemap = null, _sitemapAt = 0;
const SITEMAP_TTL_MS = 60 * 60 * 1000;
const SITEMAP_CAP = 5000; // per content type
function _urlTag(loc, lastmod, changefreq, priority) {
    return `<url><loc>${esc(abs(loc))}</loc>` +
        (lastmod ? `<lastmod>${esc(lastmod)}</lastmod>` : '') +
        (changefreq ? `<changefreq>${changefreq}</changefreq>` : '') +
        (priority ? `<priority>${priority}</priority>` : '') + `</url>`;
}
function buildSitemap() {
    const urls = [];
    const statics = [['/', 'daily', '1.0'], ['/vods', 'hourly', '0.8'], ['/clips', 'hourly', '0.8'], ['/pastes', 'hourly', '0.7'], ['/chat', 'daily', '0.5']];
    for (const [u, cf, pr] of statics) urls.push(_urlTag(u, null, cf, pr));
    try {
        for (const v of (db.getPublicVods(SITEMAP_CAP, 0) || [])) urls.push(_urlTag(`/vod/${v.id}`, isoDate(v.created_at), 'weekly', '0.6'));
    } catch { /* */ }
    try {
        for (const c of (db.getPublicClips(SITEMAP_CAP, 0) || [])) urls.push(_urlTag(`/clip/${c.id}`, isoDate(c.created_at), 'weekly', '0.6'));
    } catch { /* */ }
    try {
        let off = 0;
        while (off < SITEMAP_CAP) {
            const r = db.listPastes({ visibility: 'public', limit: 200, offset: off });
            const rows = (r && r.pastes) || [];
            for (const x of rows) if (!Number(x.is_nsfw)) urls.push(_urlTag(`/p/${x.slug}`, isoDate(x.created_at), 'monthly', '0.4'));
            if (rows.length < 200 || off + 200 >= (r && r.total ? r.total : 0)) break;
            off += 200;
        }
    } catch { /* */ }
    try {
        const chans = new Map();
        for (const s of (db.listVodStreamers ? db.listVodStreamers() : [])) chans.set(s.username, s);
        for (const s of (db.listClipStreamers ? db.listClipStreamers() : [])) chans.set(s.username, s);
        for (const u of chans.keys()) if (u) urls.push(_urlTag(`/@${u}`, null, 'daily', '0.6'));
    } catch { /* */ }
    return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.join('\n')}\n</urlset>`;
}
function sitemapHandler(req, res) {
    if (!_sitemap || (Date.now() - _sitemapAt) > SITEMAP_TTL_MS) {
        try { _sitemap = buildSitemap(); _sitemapAt = Date.now(); }
        catch (e) { console.warn('[SEO] sitemap build failed:', e.message); if (!_sitemap) return res.status(500).end(); }
    }
    res.set('Content-Type', 'application/xml; charset=utf-8');
    res.set('Cache-Control', 'public, max-age=3600');
    res.send(_sitemap);
}

// Register: dynamic sitemap first, then the meta middleware. MUST be mounted BEFORE
// express.static (so it can intercept "/") and before the SPA catch-all.
function register(app) {
    app.get('/sitemap.xml', sitemapHandler);
    app.use(middleware);
    console.log('[SEO] per-route meta + dynamic sitemap registered');
}

module.exports = { register, middleware, sitemapHandler, buildSitemap, _pageMeta, render };
