/**
 * Reusable server-side clip cutter — cuts a clip from any source ffmpeg can read (a local
 * VOD/recording file OR a presigned B2/R2 URL) and creates the clip row + thumbnail + AI
 * overview. Shared by the AI auto-clip job (live + VOD). No req/res coupling.
 */
const fs = require('node:fs');
const path = require('node:path');
const { spawn } = require('node:child_process');
const db = require('../db/database');
let config = null; try { config = require('../config'); } catch { /* */ }

const CLIPS_DIR = path.resolve((config && config.vod && config.vod.clipsPath) || './data/clips');
const MAX_CONCURRENT = 2;
let _active = 0;

function _ffprobe(file) {
    return new Promise((resolve) => {
        const ff = spawn('ffprobe', ['-v', 'error', '-print_format', 'json', '-show_format', '-show_streams', file], { stdio: ['ignore', 'pipe', 'ignore'] });
        let out = '';
        ff.stdout.on('data', d => { out += d; });
        const to = setTimeout(() => { try { ff.kill('SIGKILL'); } catch { /* */ } resolve(null); }, 15000);
        ff.on('close', () => { clearTimeout(to); try { resolve(JSON.parse(out)); } catch { resolve(null); } });
        ff.on('error', () => { clearTimeout(to); resolve(null); });
    });
}

/**
 * Cut a clip. Returns the created clip row, or null on failure.
 * @param {object} o
 * @param {string} o.source     local path OR http(s) URL ffmpeg can read
 * @param {number} o.startTime  seconds into the source to start
 * @param {number} o.duration   clip length in seconds
 * @param {number} o.streamId   owning stream
 * @param {number} o.vodId      owning VOD (optional)
 * @param {number} o.userId     clip owner (usually the streamer)
 * @param {string} o.title      clip title
 * @param {string} o.description
 * @param {number|boolean} o.isPublic
 * @param {boolean} o.autoGenerated
 */
async function cutClip(o) {
    const { source, startTime, duration, streamId, vodId = null, userId, title, description = '', isPublic = 1, autoGenerated = true } = o || {};
    if (!source || !userId || !(duration >= 1)) return null;
    const isUrl = /^https?:\/\//i.test(String(source));
    if (!isUrl && !fs.existsSync(source)) return null;
    if (_active >= MAX_CONCURRENT) return null; // don't pile up ffmpeg jobs
    try { if (!fs.existsSync(CLIPS_DIR)) fs.mkdirSync(CLIPS_DIR, { recursive: true }); } catch { /* */ }

    const ss = Math.max(0, Number(startTime) || 0);
    const dur = Math.max(1, Number(duration) || 20);
    const filename = `clip-${Date.now()}-${Math.random().toString(36).slice(2, 8)}.webm`;
    const outPath = path.join(CLIPS_DIR, filename);

    _active++;
    const ok = await new Promise((resolve) => {
        const args = [
            '-y', '-ss', String(ss), '-i', source, '-t', String(dur),
            '-c:v', 'libvpx', '-b:v', '2000k', '-crf', '18', '-deadline', 'realtime', '-cpu-used', '4',
            '-force_key_frames', 'expr:gte(t,n_forced*2)', '-c:a', 'libopus', '-b:a', '128k',
            '-avoid_negative_ts', 'make_zero', '-f', 'webm', outPath,
        ];
        const ff = spawn('ffmpeg', args, { stdio: 'ignore' });
        const to = setTimeout(() => { try { ff.kill('SIGKILL'); } catch { /* */ } resolve(false); }, Math.round(dur) * 2000 + (isUrl ? 40000 : 20000));
        ff.on('close', (code) => { clearTimeout(to); resolve(code === 0); });
        ff.on('error', () => { clearTimeout(to); resolve(false); });
    }).finally(() => { _active = Math.max(0, _active - 1); });

    if (!ok) { try { fs.existsSync(outPath) && fs.unlinkSync(outPath); } catch { /* */ } return null; }

    // Validate real decodable footage (a seek near EOF can yield a header-only file).
    const pi = await _ffprobe(outPath);
    const hasVideo = pi && (pi.streams || []).some(s => s.codec_type === 'video');
    const realDur = pi && pi.format ? Number(pi.format.duration) : 0;
    if (!hasVideo || !(realDur >= 1)) { try { fs.unlinkSync(outPath); } catch { /* */ } return null; }

    let visStr = 'public';
    try { const st = db.getStreamById(streamId); if (st && db.resolveStreamClipVisibility) visStr = db.resolveStreamClipVisibility(st); } catch { /* */ }
    const res = db.createClip({
        vod_id: vodId, stream_id: streamId, user_id: userId,
        title: (title || 'Auto Clip').slice(0, 120), description: description || '',
        file_path: outPath, start_time: ss, end_time: ss + realDur, duration_seconds: realDur,
        is_public: (isPublic === 0 || isPublic === false) ? 0 : (visStr === 'public' ? 1 : 0),
        auto_generated: autoGenerated ? 1 : 0,
    });
    const clipId = res && res.lastInsertRowid;
    if (!clipId) return null;
    try { if (db.setClipVisibility) db.setClipVisibility(clipId, visStr); } catch { /* */ }
    const clip = db.getClipById(clipId);
    try { require('../thumbnails/thumbnail-service').generateClipThumbnail(clipId, outPath).catch(() => {}); } catch { /* */ }
    try { require('./clip-notify').scheduleClipNotify(clipId); } catch { /* */ }
    // If we didn't already give it an AI description, generate one.
    if (!description) { try { require('../ai/ai-analysis').generateClipOverview(clip).catch(() => {}); } catch { /* */ } }
    return clip;
}

module.exports = { cutClip };
